version: 2
updates:
  - package-ecosystem: gomod
    directory: /backend
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(deps):"

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(deps):"

  - package-ecosystem: terraform
    directory: /deploy
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(deps):"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(deps):"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(deps):"
